language: java
jdk: openjdk8

services:
  - docker

before_install:
- docker pull maven

script:
# As noted at https://docs.travis-ci.com/user/languages/java/#projects-using-maven
# Travis always runs mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# The following line runs if that succeeds
- mvn clean install