# Azure DevOps Build Pipeline
name: CloudStorageMaven_$(Build.BuildID)_$(SourceBranchName)_$(Date:yyyyMMdd)

trigger:
  - master
  - feature/*

steps:
  - task: Maven@3
    displayName: Build CloudStorageWagon
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'
      options: -B
      publishJUnitResults: false
      jdkVersionOption: '1.8'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'AzureStorageWagon/target/azure-storage-wagon.jar'
      artifactName: 'azure-storage-wagon'
      publishLocation: 'Container'
